# Variables to reduce noise
[variables]
    NPM_CONFIG_UPDATE_NOTIFIER = 'false'
    NPM_CONFIG_FUND = 'false'

# Install PHP & required extensions
[phases.setup]
    aptPkgs = [
        "php", "php-cli", "php-mbstring", "php-tokenizer",
        "php-xml", "php-curl", "php-bcmath", "php-zip"
    ]

# Install Caddy
[phases.caddy]
    dependsOn = ['setup']
    nixpkgsArchive = 'ba913eda2df8eb72147259189d55932012df6301'
    nixPkgs = ['caddy']

# Format Caddyfile
[phases.fmt]
    dependsOn = ['caddy']
    cmds = ['caddy fmt --overwrite Caddyfile']

# Start both PHP-FPM and Caddy
[start]
    cmd = 'caddy run --config Caddyfile --adapter caddyfile 2>&'

